### ISSUE TITLE
Перемещение HLSR в другую папку

### ISSUE THREAD

**Issue by TheSirCororo** [InfiniteC0re/HLSR#1]
Я переместил HLSR в другую папку (и папку из AppData/Local/Programs/HLSR, и папку не помню откуда, короче все папки переместил в 1 папку), поменял в library.json путь на новый путь, но ничего не поменялось - игры не установлены, язык английский и т.п. Как правильно это сделать?

**Comment by InfiniteC0re** [comment]
папку AppData\Roaming\hlsr перемещать нельзя, конфигурации в любом случае будут находиться в ней. путь для установки игр можно установить при загрузке первой игры в лаунчере. также проверь путь в library.json - libraryPath

**Comment by TheSirCororo** [comment]
У меня получилось так, что все папки оказались в одной папке.
Напиши что должно быть в AppData\Roaming\hlsr, я туда верну, в library.json поставлен новый путь

**Comment by InfiniteC0re** [comment]
папка library, если она есть там, а также все json файлы

**Comment by TheSirCororo** [comment]
Это то, от чего я избавлялся, т.к. мне надо освободить место на диске C:\, а папка library самая увесистая

**Comment by TheSirCororo** [comment]
Сделай возможность конфигурировать место папки library

**Comment by InfiniteC0re** [comment]
libraryPath в library.json за это и отвечает. в новых версиях при установке первой игры ты можешь выбрать путь для установки и не устанавливать не только на диск C. если путь в library.json ты изменил, то просто закинь этот файл в AppData\Roaming\hlsr, без папки library

**Comment by TheSirCororo** [comment]
Спасибо, я это исправил
