### ISSUE TITLE
[HL2:GHOSTING] Не запускается

### ISSUE THREAD

**Issue by ghost** [InfiniteC0re/HLSR#2]
Оставил на установку HL2 Ghosing, на 100 % hlsr завис, а через время престал отвечать. Я перезапустил hlsr и в разделе Игры ничего не было, только предлагало заново установить.
Запускал саму hl2(которая уже установилась) через SSE, но тщедно. Пере распаковывал архив с ghosting и запускал, но hl2 все по прежнему виснет.

**Comment by InfiniteC0re** [comment]
fixed with [298b370845d6d7bdcceceef25048411b93cbae09](https://github.com/InfiniteC0re/HLSR/commit/298b370845d6d7bdcceceef25048411b93cbae09) commit
